In [3]:
import tensorflow as tf
import numpy as np
tf.__version__

'2.0.0'

In [4]:
tf.constant(6)

<tf.Tensor: id=0, shape=(), dtype=int32, numpy=6>

In [5]:
tf.constant(6.)

<tf.Tensor: id=1, shape=(), dtype=float32, numpy=6.0>

In [6]:
tf.constant([True, False])

<tf.Tensor: id=2, shape=(2,), dtype=bool, numpy=array([ True, False])>

In [7]:
tf.constant('I love TF')

<tf.Tensor: id=3, shape=(), dtype=string, numpy=b'I love TF'>

In [8]:
a = tf.constant([1,2,3])
print(a)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [9]:
a = np.array([1,2,3])
b = tf.convert_to_tensor(a)
print(a)
print(b)

[1 2 3]
tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [17]:
a = tf.ones(6)
b = tf.Variable(a, name='Data_point')

In [19]:
# check tf.Variable
b.dtype

tf.float32

In [20]:
b.name

'Data_point:0'

In [21]:
b.trainable

True

In [26]:
# Example of create zero
a = tf.zeros([6,6])
a

<tf.Tensor: id=76, shape=(6, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [27]:
b = tf.zeros_like(a)
b

<tf.Tensor: id=77, shape=(6, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [28]:
c = tf.fill([6,6], 0)
c

<tf.Tensor: id=80, shape=(6, 6), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)>

In [31]:
# Example random by normal distribution
a = tf.random.normal([6,6], mean = 0, stddev = 1)
a

<tf.Tensor: id=92, shape=(6, 6), dtype=float32, numpy=
array([[-0.01813317,  0.59496486, -0.10287994, -0.03476705, -1.012172  ,
         0.15744112],
       [-0.9477086 , -0.3335474 , -0.97094774,  0.49443418, -0.09851271,
        -0.5408863 ],
       [-0.9768823 , -1.1362982 ,  0.36085612,  1.487743  ,  0.09747643,
        -2.1391566 ],
       [ 1.718244  ,  1.8086684 ,  0.21853128, -1.5289762 ,  0.21162604,
        -0.6782936 ],
       [ 1.18307   ,  0.17094716,  1.4607472 , -1.8871611 , -0.7606457 ,
         0.03821288],
       [-0.3770435 ,  0.369909  , -0.70073086, -0.33597702, -1.1452011 ,
         1.0820594 ]], dtype=float32)>

In [ ]:
# random by truncated normal distribution
b = tf.random.truncated_normal([6,6], mean = 0, )