In [2]:
import tensorflow as tf
import numpy as np
tf.__version__

'2.0.0'

In [3]:
tf.constant(6)

<tf.Tensor: id=0, shape=(), dtype=int32, numpy=6>

In [4]:
tf.constant(6.)

<tf.Tensor: id=1, shape=(), dtype=float32, numpy=6.0>

In [5]:
tf.constant([True, False])

<tf.Tensor: id=2, shape=(2,), dtype=bool, numpy=array([ True, False])>

In [6]:
tf.constant('I love TF')

<tf.Tensor: id=3, shape=(), dtype=string, numpy=b'I love TF'>

In [7]:
a = tf.constant([1,2,3])
print(a)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [8]:
a = np.array([1,2,3])
b = tf.convert_to_tensor(a)
print(a)
print(b)

[1 2 3]
tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [9]:
a = tf.ones(6)
b = tf.Variable(a, name='Data_point')

In [10]:
# check tf.Variable
b.dtype

tf.float32

In [11]:
b.name

'Data_point:0'

In [12]:
b.trainable

True

In [13]:
# Example of create zero
a = tf.zeros([6,6])
a

<tf.Tensor: id=18, shape=(6, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [14]:
b = tf.zeros_like(a)
b

<tf.Tensor: id=19, shape=(6, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [15]:
c = tf.fill([6,6], 0)
c

<tf.Tensor: id=22, shape=(6, 6), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)>

In [16]:
# Example random by normal distribution
a = tf.random.normal([6,6], mean = 0, stddev = 1)
a

<tf.Tensor: id=28, shape=(6, 6), dtype=float32, numpy=
array([[ 0.23475045,  0.19531126, -0.8858946 ,  0.0140976 ,  1.7329364 ,
        -1.0714662 ],
       [-0.3086168 ,  0.646163  ,  2.1453652 ,  1.0891203 ,  0.81902164,
        -0.60064346],
       [-1.3030853 , -0.25428003, -0.6399623 , -0.25463837, -0.18158324,
        -0.7568225 ],
       [ 0.80979234, -1.080822  , -0.50929105,  1.2413712 ,  1.7243938 ,
        -0.6058285 ],
       [-0.5082742 ,  0.08469547, -0.29255038, -0.07362638, -1.9127594 ,
        -0.01593612],
       [-0.23517732, -2.525139  ,  0.32221758,  1.4899458 ,  0.4421446 ,
        -1.2337537 ]], dtype=float32)>

In [18]:
# random by truncated normal distribution
b = tf.random.truncated_normal([6,6], mean = 0, )
b

<tf.Tensor: id=40, shape=(6, 6), dtype=float32, numpy=
array([[ 0.65965223, -0.24354482,  1.0908871 ,  0.2218329 , -0.20379417,
         0.3702346 ],
       [-0.9064443 ,  0.8928901 ,  1.4626251 ,  0.1675419 , -1.1436559 ,
        -0.6087246 ],
       [ 1.1697145 ,  1.6262107 , -0.19048119, -0.27591667,  1.8814676 ,
         0.14600946],
       [ 1.3420037 ,  0.244721  ,  0.8104963 ,  0.36584204,  0.73588574,
         0.32315874],
       [-0.40275487,  1.4657907 , -1.3698874 , -1.0222567 ,  0.6391265 ,
         0.2925666 ],
       [-0.02646762,  1.0354882 , -1.2407523 ,  0.386618  ,  0.881666  ,
        -0.7553224 ]], dtype=float32)>

In [19]:
# Exmaple for select instance
a = tf.ones([1,5,5,3])

In [20]:
a[0][0].shape

TensorShape([5, 3])

In [21]:
a[...,2].shape

TensorShape([1, 5, 5])

In [22]:
tf.gather_nd(a, [0]).shape

TensorShape([5, 5, 3])